# Generated by Django 3.0.8 on 2020-07-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('example1', models.TextField(max_length=400)),
                ('example2', models.TextField(max_length=400)),
                ('example3', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('word', models.ManyToManyField(to='flash.Card')),
            ],
        ),
    ]
