# Generated by Django 3.0.8 on 2020-07-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='description',
            new_name='meaning',
        ),
    ]
