# Generated by Django 3.0.8 on 2020-07-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_auto_20200708_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.ManyToManyField(blank=True, null=True, to='flash.Card'),
        ),
    ]
