# Generated by Django 3.0.8 on 2020-07-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0004_auto_20200709_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.ManyToManyField(to='flash.Card'),
        ),
    ]
