# Generated by Django 5.0.4 on 2024-04-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0005_auto_20200709_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Topic',
        ),
    ]
