# Generated by Django 5.0.4 on 2024-04-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0006_auto_20240406_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='word',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='word',
            new_name='topic',
        ),
    ]
