# Generated by Django 5.0.4 on 2024-04-06 20:44

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0007_auto_20240406_1301'),
    ]


    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='meaning',
            new_name='description',
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='flash.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_topic1', to='flash.topic')),
                ('topic2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_topic2', to='flash.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_rows', to='flash.comparison')),
                ('keyword', models.CharField(max_length=200)),
                ('row1', models.TextField()),
                ('row2', models.TextField()),
            ],
        ),
    ]
