# Generated by Django 5.0.4 on 2024-05-02 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0009_auto_20240406_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='topic1',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='topic2',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='example1',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='example2',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='example3',
        ),
        migrations.AddField(
            model_name='comparison',
            name='comparison1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='comparison2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flash.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
