# Generated by Django 5.0.4 on 2024-05-05 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0010_remove_comparison_topic1_remove_comparison_topic2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='flash.topic'),
        ),
    ]
